---
output:
  pdf_document: default
  html_document: default
---

```{r, message = FALSE,echo=FALSE, warning=FALSE}
suppressWarnings(library(rmarkdown))
```




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r table-simple, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
suppressWarnings(require(pander))
panderOptions('table.split.table', Inf)
set.caption("2×2 contigency table")

my.data <- "
TestResults | Patient_w_D | Healthy_Control | Total
Elev_C      |     4       |        2        |   6
Norm_C      |     1       |        3        |   4
Total       |     5       |        5        |  10
"
df <- read.delim(textConnection(my.data),header=FALSE,sep="|",strip.white=TRUE,stringsAsFactors=FALSE)
names(df) <- unname(as.list(df[1,])) # put headers on
df <- df[-1,] # remove first row
row.names(df)<-NULL
pander(df, style = 'rmarkdown')


panderOptions('table.split.table', Inf)
set.caption("2×2 contigency table -- expected")

my.data <- "
TestResults | Patient_w_D | Healthy_Control | Total
Elev_C      |     3       |        3        |   6
Norm_C      |     2       |        2        |   4
Total       |     5       |        5        |  10
"
df <- read.delim(textConnection(my.data),header=FALSE,sep="|",strip.white=TRUE,stringsAsFactors=FALSE)
names(df) <- unname(as.list(df[1,])) # put headers on
df <- df[-1,] # remove first row
row.names(df)<-NULL
pander(df, style = 'rmarkdown')

```